version: '3.8'
services:
   rabbitmq:
    image: "bitnami/rabbitmq:latest"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"

   celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=user
      - AMQP_PASSWORD=bitnami
      - AMQP_ADMIN_USERNAME=user
      - AMQP_ADMIN_PASSWORD=bitnami
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

   web:
      build: .    
      command: bash -c "alembic upgrade head && python main.py"
      ports:
         - 8000:8000

   worker:
      build: .
      depends_on:
         - rabbitmq
      command: "celery -A tasks.check_currency worker -E -B --loglevel=INFO"